[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#24483e"
backgroundColor = "#fffdf7"
secondaryBackgroundColor = "#edf4e7"
textColor = "#24483e"
font = "sans serif"
